Remove Pinpoint resources from Terraform state before destroy command
Terraform can't query for the status of Pinpoint resources apparently:

```
Error: reading Pinpoint Email Channel (faa6217a37b14f92af57b4aaa5e94c23): operation error Pinpoint: GetEmailChannel, https response error StatusCode: 0, RequestID: , request send failed, Get "https://pinpoint.
us-east-1.amazonaws.com/v1/apps/faa6217a37b14f92af57b4aaa5e94c23/channels/email": dial tcp: lookup pinpoint.us-east-1.amazonaws.com on 127.0.0.53:53: no such host
```

So avoid triggering those calls by removing the resources from
Terraform's view. The Pinpoint resources then need to be deleted
manually.